name: Deploy xray Document
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - closed
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rsync files
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz
          path: ./
          remote_path: /home/github/docs
          remote_host: 47.243.170.92
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
