name: SSH Connection Test

on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -T github@47.243.170.92
